# Default values for the KubeRay TPU webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
tpuWebhook:
  namespace:
    name: ray-system
    labels: {}
  
  image:
    repository: us-docker.pkg.dev/ai-on-gke/kuberay-tpu-webhook/tpu-webhook
    tag: v1.2.5-gke.1
    pullPolicy: IfNotPresent

  deployment:
    replicas: 1
    verbosity: 0
    bindPort: 443
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        add:
        - "NET_BIND_SERVICE"
      readOnlyRootFilesystem: true
      runAsUser: 2007
      seccompProfile:
        type: RuntimeDefault
    podSecurityContext: {}
  
  service:
    type: ClusterIP
    port: 443

  cert:
    duration: 2160h # 90d
    renewBefore: 360h # 15d
